services:
  #APIサーバーコンテナ
  api:
    platform: linux/arm64  
    build: .
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload